#-------------------------------------------
# PROTOCOLS
#-------------------------------------------
i2c:
  - id: bus_a
    sda: GPIO19
    scl: GPIO45
    #frequency: 100kHz

spi:
  - id: lcd_spi
    clk_pin: GPIO48
    mosi_pin: GPIO47

#-------------------------------------------
# ESPHOME PLATFORM SETTINGS
#-------------------------------------------
esphome:
  name: 480display
  friendly_name: 480display
  includes:
    - custom_components/display_utils/display_utils_v2.h
    - custom_components/display_utils/battery_icon_renderer.h
    - custom_components/display_utils/climate_tile_renderer.h
  platformio_options:
    board_build.flash_mode: dio

#-------------------------------------------
# ESP MCU SETTINGS
#-------------------------------------------
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:

      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "OsQLeKQX3/JcDHVjPidAzfgMQBJVI3ECxGRrcqsSDzI="

ota:
  - platform: esphome
    password: "18f2cab93b94619f784f874bfe778092"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

globals:
  - id: display_initialized
    type: bool
    restore_value: no
    initial_value: "false"
#-------------------------------------------
# SENSORS
#-------------------------------------------
sensor:
  - platform: homeassistant
    name: "Battery Percent"
    entity_id: sensor.victron_system_battery_soc
    id: battery_percent
  - platform: homeassistant
    name: "Strompreis aktuell"
    entity_id: sensor.strompreis_aktuell
    id: strompreis_aktuell
  - platform: homeassistant
    name: "OfficeBot Power"
    entity_id: sensor.officebot_stromverbrauch_gesamt
    id: officebot_stromverbrauch_gesamt
  - platform: homeassistant
    name: "Victron In Power"
    entity_id: sensor.shelly_victron_in_power
    id: shelly_victron_in_power
  - platform: homeassistant
    name: "Spannung"
    entity_id: sensor.victron_system_battery_voltage
    id: battery_voltage
  - platform: homeassistant
    name: "Temp Dane Office"
    entity_id: sensor.shellyhtg3_3030f9e6559c_temperature
    id: temperature_dane_office
  - platform: homeassistant
    name: "Shelly In State"
    entity_id: switch.shelly_victron_in
    id: shelly_victron_in_state
    on_value:
      then:
        - lambda: |-
            ESP_LOGI("Sensor", "Shelly In state changed");
            id(st7701_display)->update();  // Display explizit aktualisieren
  - platform: homeassistant
    name: "Climate Target"
    entity_id: climate.thermostat_office_dane_thermostat
    attribute: temperature
    id: climate_dane_target

  - platform: homeassistant
    name: "Climate Current"
    entity_id: climate.thermostat_office_dane_thermostat
    attribute: current_temperature
    id: climate_dane_current

switch:
  - platform: homeassistant
    name: "Shelly In"
    entity_id: switch.shelly_victron_in
    id: shelly_victron_in

binary_sensor:


#-------------------------------------------
# GT911 touchscreen sensor
#-------------------------------------------
  - platform: gt911
    name: "Home"
    index: 0
   
#-------------------------------------------
# OUTPUTS
#-------------------------------------------
output:
  - platform: ledc
    pin: GPIO38
    id: backlight
    frequency: 100Hz

#-------------------------------------------
# LIGHTS
#-------------------------------------------
light:
  - platform: monochromatic
    output: backlight
    name: Display Backlight
    id: display_backlight
    restore_mode: ALWAYS_ON

# I/O expander. Touchscreen RESET and INTERRUPT are not used.
pca9554:
  - id: p_c_a
    pin_count: 16
    address: 0x20

touchscreen:
  platform: gt911
  #rotation: 180
  transform:
    mirror_x: true
    mirror_y: true
  id: my_touchscreen
  display: st7701_display
  
  on_touch:
    - logger.log:
        format: Touch at raw (%d, %d) normalized (%d, %d)
        args: [touch.x_raw, touch.y_raw, touch.x, touch.y]
    - lambda: |-
        // Rotation aus der Displaykonfiguration (manuell festlegen)
        int rotation = 0;  // Ändere dies je nach Displayrotation

        // Original-Touch-Koordinaten loggen
        ESP_LOGI("cal", "Original Touch: x=%d, y=%d, x_raw=%d, y_raw=%d", touch.x, touch.y, touch.x_raw, touch.y_raw);

        // Koordinaten basierend auf Rotation transformieren
        int rotated_x, rotated_y;
        if (rotation == 0) {
          rotated_x = touch.x;
          rotated_y = touch.y;
        } else if (rotation == 90) {
          rotated_x = touch.y;
          rotated_y = 480 - touch.x;
        } else if (rotation == 180) {
          rotated_x = 480 - touch.x;
          rotated_y = 480 - touch.y;
        } else if (rotation == 270) {
          rotated_x = 480 - touch.y;
          rotated_y = touch.x;
        } else {
          ESP_LOGW("cal", "Unsupported rotation value: %d", rotation);
          rotated_x = touch.x;
          rotated_y = touch.y;
        }

        // Transformierte Koordinaten loggen
        ESP_LOGI("cal", "Rotated Touch: rotated_x=%d, rotated_y=%d", rotated_x, rotated_y);

        int tile_w = 480 / 2;
        int tile_h = 480 / 3;
        int col = (touch.x / tile_w) + 1;
        int row = (touch.y / tile_h) + 1;
        int local_x = touch.x % tile_w;
        ESP_LOGI("Touch", "Touch at row=%d col=%d local_x=%d", row, col, local_x);
        auto &display_utils = get_display_utils();
        display_utils.dispatch_touch(row, col, local_x, tile_w);
    
image:
  - file: "./img/ttgo_bg_480.png"
    id: img_bg
    resize: 480x480
    type: rgb
   
    
font:
  - file: "gfonts://Roboto Condensed"
    id: roboto_12
    size: 12
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_14
    size: 14
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_16
    size: 16
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_18
    size: 18
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_20
    size: 20
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_25
    size: 25
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_30
    size: 30
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_35
    size: 35
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_40
    size: 40
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_45
    size: 45
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_50
    size: 50
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_60
    size: 60
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_70
    size: 70
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_80
    size: 80
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "
  - file: "gfonts://Roboto Condensed"
    id: roboto_90
    size: 90
    glyphs: 
      - "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜabcdefghijklmnopqrstuvwxyzäöü!@#$%^&*()_+-=[]{}|;:',.<>?/\"€° "

display:
  - platform: st7701s
    id: st7701_display
    rotation: 0
    update_interval: 5s
    auto_clear_enabled: false
    data_rate: 8MHz
    spi_mode: MODE3
    color_order: RGB
    dimensions:
      width: 480
      height: 480
    invert_colors: false
    transform:
      mirror_x: true
      mirror_y: true
    cs_pin: 39
      # reset not defined 
    reset_pin: # CONNECTED TO GND
      pca9554: p_c_a
      number: 5
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    init_sequence: 
      - 1
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10] # CMD2_BKSEL_BK0
      - [0xCD, 0x00] # disable MDT flag
    pclk_frequency: 12MHz
    pclk_inverted: false
    data_pins:
      red:
        - 11         # R1
        - 12         # R2
        - 13         # R3
        - 14         # R4
        - 0          # R5
      green:
        - 8          # G0
        - 20         # G1
        - 3          # G2
        - 46         # G3
        - 9          # G4
        - 10         # G5 
      blue:
        - 4          # B1
        - 5          # B2
        - 6          # B3
        - 7          # B4
        - 15         # B5

    lambda: |-
      auto &display_utils = get_display_utils();
      // Initialisierungen nur einmal durchführen
      if (!id(display_initialized)) {
        display_utils.roboto_12 = id(roboto_12);
        display_utils.roboto_14 = id(roboto_14);
        display_utils.roboto_16 = id(roboto_16);
        display_utils.roboto_18 = id(roboto_18);
        display_utils.roboto_20 = id(roboto_20);
        display_utils.roboto_25 = id(roboto_25);
        display_utils.roboto_30 = id(roboto_30);
        display_utils.roboto_35 = id(roboto_35);
        display_utils.roboto_40 = id(roboto_40);
        display_utils.roboto_45 = id(roboto_45);
        display_utils.roboto_50 = id(roboto_50);
        display_utils.roboto_60 = id(roboto_60);
        display_utils.roboto_70 = id(roboto_70);
        display_utils.roboto_80 = id(roboto_80);
        display_utils.roboto_90 = id(roboto_90);
        display_utils.image_bg = id(img_bg);
        display_utils.set_grid(480, 480, 2, 3, 0, 0);
        display_utils.register_action_handler("toggle_victron", []() {
          ESP_LOGI("Touch", "TOGGLE ACTION FIRED");
          if (id(shelly_victron_in).state)
            id(shelly_victron_in).turn_off();
          else
            id(shelly_victron_in).turn_on();
          });
        display_utils.register_action_handler("climate_down", []() {
          id(climate_dane_target).publish_state(id(climate_dane_target).state - 1.0f);
        });
        display_utils.register_action_handler("climate_up", []() {
          id(climate_dane_target).publish_state(id(climate_dane_target).state + 1.0f);
        });
        display_utils.render_battery_tile(it, 1, 1, "AKKU LADESTAND", id(battery_percent).state, "999999");
        display_utils.render_tile_compact(it, 2, 1, "AKKU VOLT", id(battery_voltage).state, " V", "%.1f", "999999");
        display_utils.render_tile_compact(it, 1, 2, "STROMPREIS", id(strompreis_aktuell).state, "€", "%.2f", "999999");
        display_utils.render_tile_compact(it, 2, 2, "BOT LEISTUNG", id(officebot_stromverbrauch_gesamt).state, " W", "%.0f", "999999");
        display_utils.render_tile_compact(it, 1, 3, "AKKU LADEN", 0, "", "%.0f", "999999", {{DisplayUtils::TouchArea::CENTER, "toggle_victron"}});
        display_utils.render_climate_tile(it, 2, 3, "CLIMATE", id(climate_dane_target).state, id(climate_dane_current).state, "999999", {{DisplayUtils::TouchArea::LEFT, "climate_down"},{DisplayUtils::TouchArea::RIGHT, "climate_up"}});
        id(display_initialized) = true;
      }

      display_utils.update_battery_tile_if_changed(it, 1, 1, id(battery_percent).state);
      display_utils.update_value_if_changed(it, 2, 1, id(battery_voltage).state, " V", "%.1f");
      display_utils.update_value_if_changed(it, 1, 2, id(strompreis_aktuell).state, "€", "%.2f");
      display_utils.update_value_if_changed(it, 2, 2, id(officebot_stromverbrauch_gesamt).state, " W", "%.0f");
      display_utils.update_value_if_changed(it, 1, 3, id(shelly_victron_in).state ? "ON" : "OFF");
      display_utils.update_climate_tile_if_changed(it, 2, 3, id(climate_dane_target).state, id(climate_dane_current).state);

