esphome:
  name: diba5
  friendly_name: Diba 5
  project:
    name: esphome.diba5
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Common components to get started
logger:

api:

ota:

# Example Wi-Fi configuration (user needs to fill this in)
# wifi:
#   ssid: "YourSSID"
#   password: "YourPassword"
#   # Optional:
#   # manual_ip:
#   #   static_ip: 192.168.1.123
#   #   gateway: 192.168.1.1
#   #   subnet: 255.255.255.0
#   #   dns1: 8.8.8.8
#   #   dns2: 8.8.4.4
