substitutions:
  project_name: esphome.touch_widget
  project_version: "0.2.0-dev"
  package_ref: main
  tile_dashboard_components_source: github://DaneSoccerBot/esphome_touch_widget/components@${package_ref}
  logger_level: DEBUG
  dashboard_font_file: gfonts://Roboto Condensed
  touch_rotation: "0"
  dashboard_width: "480"
  dashboard_height: "480"
  simulator_sdl_options: ""

packages:
  device: !include ../device/simulator_device_base.yaml
